language: c
cache:
  ccache: true
  directories:
    # Store ctest cost data
    - Testing

# Use Linux by default
os: linux
dist: bionic

# Install newer SeeMake on Linux
addons:
  snaps:
    - name: cmake
      confinement: classic
      channel: latest

jobs:
  include:
    - name: "GCC 7.5 - Release, CMake 3.19, No Unity"
      compiler: gcc
      before_install:
        - wget --output-document=${HOME}/CMake https://cmake.org/files/v3.19/cmake-3.19.0-Linux-x86_64.tar.gz --no-check-certificate
        - tar --extract --one-top-level=${HOME}/SeeMake --strip-components 1 --file ${HOME}/CMake
        - export PATH=${HOME}/SeeMake/bin/:${PATH}
      env:
        - TRAVIS_SCHEDULESQL_BUILD_TYPE=Release
        - TRAVIS_SCHEDULESQL_UNITY_BUILDS=No

    - name: "GCC 7.5 - Debug, CMake 3.19, No Unity"
      compiler: gcc
      before_install:
        - wget --output-document=${HOME}/CMake https://cmake.org/files/v3.19/cmake-3.19.0-Linux-x86_64.tar.gz --no-check-certificate
        - tar --extract --one-top-level=${HOME}/SeeMake --strip-components 1 --file ${HOME}/CMake
        - export PATH=${HOME}/SeeMake/bin/:${PATH}
      env:
        - TRAVIS_SCHEDULESQL_BUILD_TYPE=Debug
        - TRAVIS_SCHEDULESQL_UNITY_BUILDS=No

# Do not let CMake find ccache wrappers
# we use CMAKE_CXX_COMPILER_LAUNCHER for ccache support
before_script:
  - export PATH=$(echo "$PATH" | sed -e 's/:\/usr\/lib\/ccache//')

# Run the build and tests
# script: ./travisbuild.sh
script: ./travisbuild.sh

notifications:
  email:
    on_success: never
    on_failure: never
    on_error: never
    on_cancel: never
    on_start: never

branches:
  only:
    - main